version: '3'
services:
  app:
    build: .
    environment:
      - DB_HOST=postgresql_database
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
      - DB_NAME=productDb
      - DB_PORT=5432
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresql_database

  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=productDb
    ports:
      - "5432:5432"
    restart: always