version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=godb
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=godb
      - PORT=8080
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8080:8080
    links:
      - db
volumes:
  db:
    driver: local